server:
  port: 7002 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称

eureka:
  instance:
    hostname: eureka1.com #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      #集群指向其它eureka
      defaultZone: http://eureka.com:7001/eureka/
      #单机就是7001自己
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #  server:
  #关闭自我保护机制，保证不可用服务被及时踢除
  #enable-self-preservation: false


