server:
  port: 9999

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
#        - id: payment_route1
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/get/**
#        - id: payment_route2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
        - id: payment_route1
          uri: lb://CLOUD-PAYMENT
          predicates:
            - Path=/payment/get/**
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，使用微服务名
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka