server:
  port: 8001
spring:
  application:
    name: sentinel-service-test
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848   #nacos服务注册中心
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: "*"
