server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment: #rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合
        input: #通道的名称
          destination: studeyExchange  #定义使用的exchange的名称
          content-type: application/json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          # group: groupA
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2   #心跳间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5  #超时时间间隔（默认90秒）
    instance-id: send-reciever2
    prefer-ip-address: true